I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    scene bg futon day
Exception: Image 'bg futon' does not accept attributes 'day'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    scene bg futon day
  File "renpy/ast.py", line 1328, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/image.py", line 438, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'bg futon' does not accept attributes 'day'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Tsundere Paradise 0.1
Sun Feb  6 16:20:35 2022
